
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Apr 01 13:35:44 EDT 2013
//----------------------------------------------------

package parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING = 9;
  public static final int RBRACE = 13;
  public static final int PUBLIC = 5;
  public static final int INT = 20;
  public static final int RBRACK = 17;
  public static final int PRINTLN = 24;
  public static final int LBRACE = 12;
  public static final int MINUS = 34;
  public static final int AND = 31;
  public static final int SEMICOLON = 18;
  public static final int LT = 32;
  public static final int LBRACK = 16;
  public static final int COMMA = 19;
  public static final int CLASS = 4;
  public static final int PLUS = 33;
  public static final int IF = 22;
  public static final int MAIN = 8;
  public static final int ASSIGN = 25;
  public static final int THIS = 29;
  public static final int DOT = 36;
  public static final int RETURN = 10;
  public static final int ID = 2;
  public static final int BOOLEAN = 21;
  public static final int EOF = 0;
  public static final int EXCLAMATION = 37;
  public static final int TRUE = 27;
  public static final int error = 1;
  public static final int NEW = 30;
  public static final int VOID = 7;
  public static final int TIMES = 35;
  public static final int STATIC = 6;
  public static final int RPAREN = 15;
  public static final int ELSE = 11;
  public static final int WHILE = 23;
  public static final int LPAREN = 14;
  public static final int FALSE = 28;
  public static final int LENGTH = 26;
  public static final int INTEGER_LITERAL = 3;
}

